theme: jekyll-theme-cayman
description: "This is a demo website for reproducible workshop series"
title: "Reproducible Research Workshops"
navbar:
 title: ""
 left:
  - text: "Home"
    href: index.md
